name: SLACK NOTIFY
on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"blocks": [{"type": "section","text":{"type": "mrkdwn","text": "Hello, World"}}]}'
