name: SLACK NOTIFY
on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - run: echo Merry Christmas
      - name: Notify
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "*メリークリスマス！！*"
                        }
                    },
                    {
                        "type": "divider"
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "*自分へのプレゼントメッセージだよ！*\n:star::star::star::star: \n 今年も終わりが近いから健康に過ごしてね。美味しい食べ物沢山食べるんだ！"
                        },
                        "accessory": {
                            "type": "image",
                            "image_url": "https://shop.letao.jp/client_info/LETAO/itemimage/R802/PC/R802_01.jpg",
                            "alt_text": "alt text for image"
                        }
                    },
                    {
                        "type": "divider"
                    }
                ]
            }
